const samples = [
  'Kapouey',
  'douze lefaut',
  'fruits et lugubres',
  'hippo-potheque',
  'je suis putréfié',
  'qui va se faire buter',
  'cette baignoire remplie',
  'ma femme a tous vos livres',
  'perspicace',
  'les petites bêtes',
  'ça va faire pouf',
  'une silhouette',
  'je lui chantais du jazz',
  'les galippeurs',
  'tumbleweeds',
  'Shit God Damn',
  'mary is a girl',
  'rire 1',
  "accordéon",
  "ça ressemble à d'la",
  "ces gens con",
  "correspondant L.A.",
  "Cri",
  "dieu qu'il est laid",
  "Est ce qu'il y a un hôtel",
  "gouvernement",
  "grabenwite",
  "grabenwite-2",
  "je veux m'occuper des R",
  "jingle 1",
  "jingle 2",
  "la fuite",
  "la fuite-2",
  "la violence faite aux chevreuil",
  "rire 2",
  "rire 3",
  "Transcontinetal Asiatique Airlines Zone Limited",
  "Twitwi Les Copains ! ",
  "un citoyen",
];